use_frameworks!

platform :ios, '11.0'

target 'Freshpaint-AppsFlyer_Example' do
  pod 'Freshpaint-AppsFlyer', :path => '../'

  target 'Freshpaint-AppsFlyer_Tests' do
    inherit! :search_paths


  end
end
